siteTitle = "tatsuroro.com"
siteDescr = "FrontEnd Developer at Fukuoka, Japan"
siteAuthor = "tatsuroro"

siteTwitterUrl = "https://twitter.com/tatsuroro"
siteGithubUrl = "https://github.com/tatsuroro"
siteEmailUrl = "/contact/"
siteRssUrl = "#"

linkPrefix = ""
